### ISSUE TITLE
matt 7~14장 

### ISSUE THREAD

**Issue by okw0817** [ThinkAboutSoftware/DoubleMe-BookClub#10]

**Comment by okw0817** [comment]
1. 숙취 증후근
 의존성 때문에 내가 무언가를 만들어도 더 늦게까지 작업한 사람의 코드 때문에 다음 날 내가 만든 코드가 작동하지 않을 수 있다.

2. 안정된 의존성 원칙
  안정된 의존성이란 무엇인가? 소프트웨어는 변경이 쉽게 가능한 웨어라고 하는데 우리는 변동성을 지니도록 설계를 해야 한다. 

  의문
    책을 읽다보면 함수의 기능들은 추상적인 인터페이스로 빼고, 컴포넌트도 추상 컴포넌트로 빼라고 한다. 그러면 추상적인 것이 안정적인 것인가? 읽다보면 안정된 추상화 원칙이라고 나오는데 간단히 말하자면 추상화를 적당히 하라는 것으로 들린다.
    그렇다면 적당히 추상화 한다는 것은 어떤 것인가?

**Comment by jongfeel** [comment]
논의 완료
