### ISSUE TITLE
Thomas 7 ~ 14

### ISSUE THREAD

**Issue by bigstro18** [ThinkAboutSoftware/DoubleMe-BookClub#13]

**Comment by bigstro18** [comment]
SRP – 하나의 모듈은 하나의, 오직 하나의 사용자 또는 이해관계자에 대해서만 책임져야 함.
-	하나의 액터에 대해서만 책임져야 한다.
-	병합시의 문제 해결책
	데이터와 메서드를 분리한다.
	간단한 클래스를 만들어 나머지 클래스가 공유하도록 함.
	퍼사드 패턴
	퍼사드 클래스에서 정의하여 새로 나누고 새로 만든 클래스로 공유
	클래스를 유지하고 덜 중요한 메서드를 분리한다.
OCP – 소프트웨어 개체는 확장에는 열려 있어야 하고, 변경에는 닫혀 있어야 함.
-	서로 다른 목적으로 변경되는 요소를 적절하게 분리하고(SRP), 사이의 의존성을 체계화(DIP)
	컴포넌트 간 사용, 구현/상속 관계에 있어 단방향으로만 이동해야 함.
	결과적으로 레벨링이 만들어짐.
	순차적으로 종속(추이 종속성)을 피하기 위해 의존성 역전이 필요할 수 있음
	중간점 역할 생성
LSP – 치환 원칙
-	S타입 객체 각각에 T타입 객체가 있고, T타입으로 정의한 프로그램 P에서 T타입의 자리에 S타입을 넣는다 해도 P의 행위가 변하지 않는다면 S는 T의 하위타입이다.
	예외처리가 필요한 상황이 생기지 않도록 한다.
ISP – 인터페이스 분리
-	변경점이 서로 연관되어 재배포하지 않도록 각 오퍼레이션에 맞춰 인터페이스로 재배치해야함.
DIP – 추상 타입에 의존하며 구체적인 타입에 의존성을 줄여야 함.
-	변동성이 큰 구체 타입에 의존하지 않도록 조심해야한다.
	변동성이 큰 구체 클래스 참조 X
	변동성이 큰 구체 클래스에서 파생 X
	구체 함수 오버라이드 X
-	추상적인 것과 구체적인 것을 효율적으로 분리할 필요가 있음.
	제어 흐름은 소스코드 의존성과 반대로 적용한다. -> 의존성 역전
REP – 재사용 단위는 릴리즈 단위와 같다.
-	동시 업데이트의 중요성
	하나의 컴포넌트로 묶인 클래스와 모듈은 버전이 같아야 하며, 동일한 릴리즈로 추적 관리되어야 하며, 동일한 릴리즈 문서에서 공지되어야 한다.
CCP – 동일한 이유로 동일한 시점에 변경되는 클래스는 같은 컴포넌트로 묶음.
-	변경이 필요할 때 변경이 각 컴포넌트에 주는 영향을 최소화 하기 위함.
CRP – 묶지 말아야 할 클래스를 구분해야 함
-	강하게 결합되지 않은 클래스를 동일 컴포넌트에 묶지 말아야 한다.
	필요하지 않은 것에 의존하지 말아야 함

ADP – 순환적으로 의존하도록 하지 말아야 함
-	릴리즈 할 때 신경 써야 할 컴포넌트를 최소화 한다.
	추상적인 것을 추가하여 흐름을 역전시킨다.
	순환 중간에 새로운 컴포넌트를 만들어 두 컴포넌트가 의존하는 클래스를 새로운 컴포넌트에 이동시킨다.
-	시작부터 급하게 아키텍처를 만들 필요는 없다.
SDP – 더 안정적인 방향으로 의존해야 함
-	불안정성은 컴포넌트 외부 클래스에 의존하는 내부 클래스 / 
(컴포넌트 외부에서 내부에 의존하는 클래스 + 컴포넌트 외부 클래스에 의존하는 내부 클래스)로 정의할 수 있다.
	불안정성이 0에 가까울수록 안정적인 컴포넌트
	안정적인 컴포넌트는 추상적으로 쉽게 확장할 수 있어야 함.
	0에 너무 가까우면 변동이 어렵고, 1에 너무 가까우면 추상적이나 의존성이 없어 쓸모 없어진다. 중간점이 중요


저자 또한 자신이 생각하는 가장 이상적인 이라는 표현을 사용하는데, 여러 지침이 있지만 결국엔 개인의 선택의 영역에 집중해야 하는가

**Comment by jongfeel** [comment]
논의 완료
