### ISSUE TITLE
ash 7-14장 

### ISSUE THREAD

**Issue by jaehooooooo** [ThinkAboutSoftware/DoubleMe-BookClub#15]

**Comment by jaehooooooo** [comment]
챕터 정리 노트 공유 합니다.
https://jaehooooooo.notion.site/c268c00c8ac94c11b7ba8b42027c6f2f

책을 읽고 내용을 이해하려 애쓰고 있지만, 코드를 보면서 책 내용이 떠오르가 않는게 문제입니다..

**Comment by jongfeel** [comment]
논의 완료
