### ISSUE TITLE
matt 15~ 21장

### ISSUE THREAD

**Issue by okw0817** [ThinkAboutSoftware/DoubleMe-BookClub#18]

**Comment by okw0817** [comment]
# 유스케이스
시스템의 아키텍처는 시스템의 의도를 지원
- 장바구니 애플리케이션이라면, 아키텍처는 장바구니와 관련된 유스케이스를 지원.
- 아키텍처는 반드시 유스케이스를 지원해야한다.    
- 사용자가 제공해야 하는 입력, 사용자에게 보여줄 출력, 그리고 해당 출력을 생성하기 위한 처리 단계를 기술   

# 엔티티
컴퓨터 시스템 내부의 객체, 핵심 업무 데이터를 기반으로 동작하는 일련의 조그만 핵심 업무 규칙을 구체화
- 유스케이스는 엔티티에 의존하지만 엔티티는 유스케이스에 의존하지 않는다. 

# 고수준 저수준
수준이란? '입력과 출력가지의거리' 
- 입력과 출력의 거리가 멀어질 수록 고수준, 입력과 출력을 다루는 시스템이라면 저수준.   
- 좋은 아키텍처라면 각 컴포넌트를연결할 때 의존성의 방향이 컴포넌트의 수준을 기반으로 연결 되도록 만들어야 한다.   
- 저수준->고수준으로 의존 되도록 설계.      

그렇다면 번역 부분 (196 페이지) 프로그램은 어떻게 만들어야 하는가?

**Comment by jongfeel** [comment]
논의 완료
