### ISSUE TITLE
Thomas 15~21

### ISSUE THREAD

**Issue by bigstro18** [ThinkAboutSoftware/DoubleMe-BookClub#19]
컨트롤러와 상관없이 제작해야 한다는 부분에서 이전에 3d button 제작 관련하여 sdk에 너무 의존하게 되었던 점을 되짚어 보게 되었다. 일정을 탓하며 급하게 마무리 지었는데 다시 제작할 필요가 있다.

유스케이스는 QA의 테스트 개념과 유사한건가?

**Comment by jongfeel** [comment]
논의 완료
