### ISSUE TITLE
Matt Pull request

### ISSUE THREAD

**Issue by okw0817** [ThinkAboutSoftware/DoubleMe-BookClub#4]
1. 구조적 프로그래밍
 제어의 흐름을 직접적인 전환에 규칙을 부여한다.

2. 객체 지향 프로그래밍
제어 흐름의 간접적인 규칙을 부과한다.

3. 함수형 프로그래밍
할당문에 대한 규칙을 부과한다.

 계속 읽어보아도 엘런 튜링이 제시한 컴퓨터 프로그램 구조가 이후에도 바뀌지 않았고 3개의 패러다임 흐름이 프로그래머에게 권한을 박탈한다고 적혀 있는데 이 부분이 이해가 되지 않습니다. 어떤 식으로 박탈을 하고 저 3개의 패러다임이 어떤 역할을 하는지 궁금합니다.

**Comment by jongfeel** [comment]
논의 완료
